# Generated by Django 5.1.1 on 2025-08-14 11:30

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя. Только буквы, цифры и символы @/./+/-/_', max_length=150, unique=True, validators=[users.validators.username_validator, django.core.validators.RegexValidator(code='invalid', message='Имя пользователя должно содержать только буквы, цифры и символы @/./+/-/_', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
